# kaan's starship prompt (shared across OSes).

add_newline = true
format = """
$username\
$directory\
$git_branch\
$git_status\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[username]
show_always = false
style_user = "bold blue"
style_root = "bold red"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false
read_only = "  "

[git_branch]
symbol = " "
style = "bold yellow"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 2_000
format = " took [$duration](bold yellow)"
